name: AMSG
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.8
  - requests
  - numpy
  - cudatoolkit=11.1.1
  - pytorch=1.8.1=py3.8_cuda11.1_cudnn8.0.5_0
  - torchvision>=0.9.1
  - pandas>=1.2.3
  - scikit-learn>=0.24.1
  - scipy
  - zlib
  - pip
  - pip:
    - mlflow==1.16.0
    - boto3
    - botocore
    - baker
    - lief==0.11.4
    - lmdb
    - logzero
    - matplotlib
    - ipykernel
    - msgpack
    - pyzipper
    - tqdm
    - configparser
    - psutil