name: AMSG
channels:
  - defaults
  - anaconda
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.8
  - requests
  - click
  - numpy
  - cudatoolkit>=1.11.1
  - pytorch=1.8.1=py3.6_cuda10.2_cudnn7.6.5_0
  - torchvision=0.9.1=py39_cu111
  - pandas>=1.2.3
  - scikit-learn
  - scipy
  - zlib
  - pip
  - pip:
    - mlflow>=1.16.0
    - boto3
    - botocore
    - baker
    - lief>=0.11.4
    - lmdb
    - logzero
    - matplotlib
    - msgpack
    - pyzipper
    - tqdm
    - vt-py
    - waiting