name: AMSG
channels:
  - defaults
  - anaconda
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.8
  - requests
  - click
  - numpy
  - cudatoolkit>=1.11.1
  - pytorch>=1.8.1
  - torchvision>=0.9.1
  - pandas>=1.2.3
  - scikit-learn>=0.24.1
  - scipy
  - zlib
  - pip
  - pip:
    - mlflow>=1.16.0
    - boto3
    - botocore
    - baker
    - lief>=0.11.4
    - lmdb
    - logzero
    - matplotlib
    - ipykernel
    - msgpack
    - pyzipper
    - tqdm
    - lief
    - configparser
    - psutil